services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: interactive-diary-app
    container_name: interactive-diary

    command: ["python", "server.py"]
    ports:
      - "8765:8765"

    working_dir: /app

    volumes:
      - .:/app

    environment:
      PYTHONPATH: /app
      PYTHONUNBUFFERED: "1"

    env_file:
      - .env

    restart: unless-stopped

    stdin_open: true
    tty: true